steps:
  - id: master
    name: gcr.io/kaniko-project/executor:latest
    args:
      - --destination=gcr.io/$PROJECT_ID/opentelemetry-collector/otelcol:master
      - --cache=true
      - --cache-ttl=6h
      - --cache-repo=gcr.io/$PROJECT_ID/opentelemetry-collector/otelcol/cache
      - --dockerfile=Dockerfile
      - --context=dir:///workspace
      - --reproducible
      - --skip-unused-stages=true
      - --target=otelcol
      - --build-arg=GOLANG_VERSION=${_GOLANG_VERSION}
      - --build-arg=ALPINE_VERSION=${_ALPINE_VERSION}
      - --build-arg=OTELCOL_VERSION=master
      - --build-arg=OTELCONTRIBCOL_VERSION=master

  - id: master-debug
    name: gcr.io/kaniko-project/executor:latest
    args:
      - --destination=gcr.io/$PROJECT_ID/opentelemetry-collector/otelcol:master-debug
      - --cache=true
      - --cache-ttl=6h
      - --cache-repo=gcr.io/$PROJECT_ID/opentelemetry-collector/otelcol/cache
      - --dockerfile=Dockerfile
      - --context=dir:///workspace
      - --reproducible
      - --skip-unused-stages=true
      - --target=otelcol-debug
      - --build-arg=GOLANG_VERSION=${_GOLANG_VERSION}
      - --build-arg=ALPINE_VERSION=${_ALPINE_VERSION}
      - --build-arg=OTELCOL_VERSION=master
      - --build-arg=OTELCONTRIBCOL_VERSION=master

substitutions:
  _GOLANG_VERSION: "1.15"
  _ALPINE_VERSION: "3.12"

tags: ["opentelemetry-collector.master", "opentelemetry-collector-contrib.master"]

timeout: 900s  # 15min
