steps:
  - id: latest
    name: gcr.io/kaniko-project/executor:latest
    args:
      - --destination=gcr.io/$PROJECT_ID/opentelemetry-collector/otelcol:${_OTELCOL_VERSION}
      - --destination=gcr.io/$PROJECT_ID/opentelemetry-collector/otelcol:latest
      - --cache=true
      - --cache-ttl=6h
      - --cache-repo=gcr.io/$PROJECT_ID/opentelemetry-collector/otelcol/cache
      - --dockerfile=Dockerfile
      - --context=dir:///workspace
      - --reproducible
      - --skip-unused-stages=true
      - --target=otelcol
      - --build-arg=GOLANG_VERSION=${_GOLANG_VERSION}
      - --build-arg=ALPINE_VERSION=${_ALPINE_VERSION}
      - --build-arg=OTELCOL_VERSION=${_OTELCOL_VERSION}

  - id: debug
    name: gcr.io/kaniko-project/executor:latest
    args:
      - --destination=gcr.io/$PROJECT_ID/opentelemetry-collector/otelcol:${_OTELCOL_VERSION}-debug
      - --destination=gcr.io/$PROJECT_ID/opentelemetry-collector/otelcol:debug
      - --cache=true
      - --cache-ttl=6h
      - --cache-repo=gcr.io/$PROJECT_ID/opentelemetry-collector/otelcol/cache
      - --dockerfile=Dockerfile
      - --context=dir:///workspace
      - --reproducible
      - --skip-unused-stages=true
      - --target=otelcol-debug
      - --build-arg=GOLANG_VERSION=${_GOLANG_VERSION}
      - --build-arg=ALPINE_VERSION=${_ALPINE_VERSION}
      - --build-arg=OTELCOL_VERSION=${_OTELCOL_VERSION}

substitutions:
  _GOLANG_VERSION: "1.15"
  _ALPINE_VERSION: "3.12"
  _OTELCOL_VERSION: "v0.9.0"

tags: ['opentelemetry-collector']

options:
  machineType: "N1_HIGHCPU_32"

timeout: 900s  # 15min
