version: 2.1

jobs:
  cloudbuild:
    docker:
      - image: gcr.io/google.com/cloudsdktool/cloud-sdk:alpine
    working_directory: /src/github.com/containerz-dev/opentelemetry-collector
    steps:
      - checkout
      - run:
          name: Setup Google Cloud SDK authentication
          command: |
            echo -n ${CLOUDBUILD_GOOGLE_APPLICATION_CREDENTIALS_JSON} | base64 -d | gcloud auth activate-service-account --key-file=-
      - run:
          name: Build container image on Google Cloud Builder
          command: |
            gcloud builds submit . \
              --project=${GCP_PROJECT} \
              --config=cloudbuild.yaml \
              --gcs-log-dir="gs://${GCP_PROJECT}_cloudbuild/log"

workflows:
  version: 2
  build:
    jobs:
      - cloudbuild:
          context: cloudbuild
  # update-opentelemetry-collector:
  #   jobs:
  #     - cloudbuild:
  #         context: cloudbuild
  #   triggers:
  #     - schedule:
  #         cron: "0 0 * * *"  # 00:00/day
  #         filters:
  #           branches:
  #             only:
  #               - master
